# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [6]:
print(f"The diameter of {planet} is {diameter} kilometers ")

The diameter of Earth is 12742 kilometers 


## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [8]:
list (d.values())[0][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [9]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [12]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [14]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [18]:
import pandas as pd


In [20]:
data = [['Rohith',20,'Male'],['Arjun',21,'Male'],['Ronaldo',38,'Male']]
df = pd.DataFrame(data,columns=['Name','Age','Gender'])
df


Name  Age Gender
0   Rohith   20   Male
1    Arjun   21   Male
2  Ronaldo   38   Male

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [21]:
dates=pd.date_range('01/01/2000','30/01/2000')
pd.DataFrame(dates)

0
0  2000-01-01
1  2000-01-02
2  2000-01-03
3  2000-01-04
4  2000-01-05
5  2000-01-06
6  2000-01-07
7  2000-01-08
8  2000-01-09
9  2000-01-10
10 2000-01-11
11 2000-01-12
12 2000-01-13
13 2000-01-14
14 2000-01-15
15 2000-01-16
16 2000-01-17
17 2000-01-18
18 2000-01-19
19 2000-01-20
20 2000-01-21
21 2000-01-22
22 2000-01-23
23 2000-01-24
24 2000-01-25
25 2000-01-26
26 2000-01-27
27 2000-01-28
28 2000-01-29
29 2000-01-30

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [22]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [23]:
df=pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24