# Basic Python

## 1. Split this string

In [6]:
s = "Hi there Sam!"

In [7]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [8]:
planet = "Earth"
diameter = 12742

In [12]:
print(f"The diameter of {planet} is {diameter} kilometers")

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [13]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [14]:
list(d.values())[0][3]['tricky'][3]['target'][3]
                                        

'hello'

# Numpy

In [15]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [17]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [19]:
a=np.array([1,2,3])
b=np.array([3,4,5])
np.concatenate((a,b),axis=None)

array([1, 2, 3, 3, 4, 5])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [21]:
import pandas as pd


In [24]:
data=[['Sharan',21],['Sivanesh',21],['Jishnu',20]]
df=pd.DataFrame(data,columns=['Name','Age'])
df

Name  Age
0    Sharan   21
1  Sivanesh   21
2    Jishnu   20

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [26]:
dates=pd.date_range('01/01/2023','10/02/2023')
pd.DataFrame(dates)

0
0   2023-01-01
1   2023-01-02
2   2023-01-03
3   2023-01-04
4   2023-01-05
..         ...
270 2023-09-28
271 2023-09-29
272 2023-09-30
273 2023-10-01
274 2023-10-02

[275 rows x 1 columns]

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [27]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [28]:
df=pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24